[2025-06-26T17:40:50.818+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag.model_training scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2025-06-26T17:40:50.820+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag.model_training scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2025-06-26T17:40:50.821+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-06-26T17:40:50.826+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): model_training> on 2024-10-01 00:00:00+00:00
[2025-06-26T17:40:50.827+0000] {standard_task_runner.py:57} INFO - Started process 40583 to run task
[2025-06-26T17:40:50.829+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag', 'model_training', 'scheduled__2024-10-01T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpidhm_9xj']
[2025-06-26T17:40:50.829+0000] {standard_task_runner.py:85} INFO - Job 169: Subtask model_training
[2025-06-26T17:40:50.845+0000] {task_command.py:416} INFO - Running <TaskInstance: dag.model_training scheduled__2024-10-01T00:00:00+00:00 [running]> on host 76c4c5836333
[2025-06-26T17:40:50.875+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T00:00:00+00:00'
[2025-06-26T17:40:50.875+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-26T17:40:50.876+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/airflow && python src/train_model.py --config configs/default_train.json']
[2025-06-26T17:40:50.878+0000] {subprocess.py:86} INFO - Output:
[2025-06-26T17:40:52.327+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-06-26T17:40:52.327+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-06-26T17:40:52.405+0000] {subprocess.py:93} INFO - 25/06/26 17:40:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-26T17:40:55.668+0000] {subprocess.py:93} INFO - Config file loaded succesfully!
[2025-06-26T17:40:55.668+0000] {subprocess.py:93} INFO - Fitting 3 folds for each of 100 candidates, totalling 300 fits
[2025-06-26T17:40:57.503+0000] {subprocess.py:93} INFO - 2025/06/26 17:40:57 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-06-26T17:40:57.503+0000] {subprocess.py:93} INFO - The git executable must be specified in one of the following ways:
[2025-06-26T17:40:57.503+0000] {subprocess.py:93} INFO -     - be included in your $PATH
[2025-06-26T17:40:57.503+0000] {subprocess.py:93} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO - 
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO - All git commands will error until this is rectified.
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO - 
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO - 
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO - Example:
[2025-06-26T17:40:57.504+0000] {subprocess.py:93} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-06-26T17:40:57.505+0000] {subprocess.py:93} INFO - 
[2025-06-26T17:40:57.541+0000] {subprocess.py:93} INFO - ML Flow is running...
[2025-06-26T17:40:57.541+0000] {subprocess.py:93} INFO - Logging current model metrics...
[2025-06-26T17:40:58.316+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-26T17:40:58.334+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag, task_id=model_training, execution_date=20241001T000000, start_date=20250626T174050, end_date=20250626T174058
[2025-06-26T17:40:58.377+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-26T17:40:58.385+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
