[2025-06-26T17:36:42.189+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: dag.data_preprocessing scheduled__2024-01-01T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-06-26T17:36:42.191+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
